name: flame_juice_box
description: "Juice up your Flame Game"
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flame: ^1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^1.1.2
  flutter_test:
    sdk: flutter
